/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(physical)": "(物理)",
    "Attack rating": "攻击等级",
    "Attack speed": "攻击速度",
    "Attributes": "属性",
    "Cast rate": "施放率",
    "Chances to block": "阻止的机会",
    "Cold": "寒冷",
    "Damage": "伤害",
    "Damage reduction": "减少伤害",
    "Defense": "防御",
    "Dexterity": "灵巧",
    "Donate": "捐赠",
    "Energy": "能量",
    "Explore the Blood Moor to begin your adventure.": "探索血之沼泽开始你的冒险。",
    "Fire": "火",
    "Freeze duration": "冻结时间",
    "Get back to the camp to get healed !": "回到营地接受治疗！",
    "Got it !": "知道了！",
    "Increase chances to find magical": "增加找到魔法的机会",
    "Increase defense and attack rating": "提高防御和攻击等级",
    "Levels": "等级",
    "Life": "生命值",
    "Lightning": "闪电",
    "Magical Damage reduction": "魔法伤害减免",
    "Mana": "法力",
    "Open Inventory": "打开仓库",
    "Options": "选项",
    "Other data": "其他数据",
    "Poison": "毒",
    "Poison duration": "中毒持续时间",
    "Quests": "任务",
    "Rakanishu": "Rakanishu",
    "Resistances": "抗性",
    "Rogue Encampment (H)": "盗贼营地 (H)",
    "Show Gold": "显示金子",
    "Show hits": "显示命中",
    "Show kills": "显示击杀",
    "Show Non-magical items": "显示非魔法物品",
    "Skills": "技能",
    "Stats": "统计",
    "Strength": "力量",
    "Stun duration": "眩晕时间",
    "Support & Credits": "支持和积分",
    "Vitality": "体力",
    "Your life is low.": "你的生命值很低。",
    "All": "全部",
    "Body": "身体",
    "Body:": "身体：",
    "Equipment": "装备",
    "Feet": "脚",
    "Feet:": "脚：",
    "Finger": "手指",
    "Finger:": "手指：",
    "Gold:": "金子：",
    "Hands": "手",
    "Hands:": "手：",
    "Head": "头",
    "Head:": "头：",
    "Inventory": "仓库",
    "Neck": "脖子",
    "Neck:": "脖子：",
    "Nothing": "无",
    "Potions": "药水",
    "Shield": "盾",
    "Shield:": "盾：",
    "Show:": "显示：",
    "Waist": "腰部",
    "Waist:": "腰部：",
    "Weapon": "武器",
    "Weapon:": "武器：",
    "Auto-pause on inventory": "打开仓库时自动暂停",
    "Clear the Den of Evil": "清除邪恶的巢穴",
    "Close": "关闭",
    "Combat": "战斗",
    "Dark mode": "深色模式",
    "Death:": "死亡：",
    "Den of Evil": "邪恶巢穴",
    "Discipline": "惩罚",
    "Download": "下载",
    "Export / Import": "导入/导出",
    "Hard reset": "硬重置",
    "Increase damages": "增加伤害",
    "Killed:": "击杀：",
    "Light mode": "浅色模式",
    "Magic": "魔法",
    "Magic Missile": "魔法飞弹",
    "Parry": "格挡",
    "Restore life": "恢复生命",
    "Shock": "冲击",
    "Summon Crow": "召唤乌鸦",
    "Quill Rat": "毛老鼠",
    "Staff": "手杖",
    "+1 to Cold Mastery (Sorceress only)": "+1 冰冷掌握（仅限女术士）",
    "Drink": "喝",
    "Equip": "装备",
    "Fallen": "堕落者",
    "Get back to the camp when your life is too low.": "当你的生活太低落时回到营地。",
    "Item dropped:": "掉落物品：",
    "Minor healing potion": "小型治疗药水",
    "Potion dropped: Minor healing potion": "掉落的药水：小型治疗药水",
    "Sell": "出售",
    "Short Staff": "短杖",
    "Two-handed": "双手",
    "Unlocked: Potion quickslots": "解锁：药水快速槽",
    "(magical)": "(魔法)",
    "(normal)": "(普通)",
    "Minor mana potion": "小法力药水",
    "Zombie": "僵尸",
    "Leather Boots": "皮靴",
    "Undead": "不死",
    "Unequip": "卸下",
    "[passive] Increase damages.": "[被动] 增加伤害。",
    "Current level:": "当前等级：",
    "Create a wave of electrical energy that deals damage and has 25% chances to stun all monsters around.": "制造一道造成伤害的电能波，并有 25% 的几率击晕周围的所有怪物。",
    "Heal.": "治疗.",
    "Increase block rate.": "提高格挡几率。",
    "Increase life & life regeneration": "提高 生命值 和 生命值恢复",
    "Launch a magic missile, dealing magical damage to 1 monster.": "发射魔法飞弹，对1只怪物造成魔法伤害。",
    "+1 Skill quickslot": "+1 快捷技能槽",
    "Summon a crow to fight for you.": "召唤乌鸦为你而战。",
    "Next level:": "下一级：",
    "Increase mana & mana regeneration": "增加法力和法力恢复",
    "+75% to resist fire for 120s": "+75% 火抗，持续 120 秒",
    "Buckler": "小圆盾",
    "Dagger": "匕首",
    "Leather Gloves": "皮手套",
    "equipped": "已装备",
    "Sash": "腰带",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "You: Miss": "你: 未命中",
    "Fallen: Miss": "堕落者：未命中",
    "Quill Rat: Miss": "毛老鼠: 未命中",
    "Zombie: Miss": "僵尸: 未命中",
    "v. beta.0.3.3 - Power of Nature": "v. beta.0.3.3 - 自然的力量",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Save ": "保存 ",
    "level ": "等级 ",
    "xp: ": "经验: ",
    "Blood Moor ": "血之沼泽 ",
    "Available points: ": "可用点数：",
    "Damage: ": "伤害: ",
    "Defense: ": "防御: ",
    "Price: ": "价格: ",
    "Speed: ": "速度: ",
    "Potion dropped: ": "药水掉落: ",
    "Restore mana: ": "恢复法力: ",
    "Restore life: ": "恢复生命值: ",
    "Required level: ": "要求等级: ",
    "Fallen died. Xp earned: ": "堕落者死了。 获得经验: ",
    "Damage inflicted: ": "造成的伤害: ",
    "Stun duration: ": "眩晕时长: ",
    "Life: ": "生命值: ",
    "Mana Cost: ": "法力成本: ",
    "Heal: ": "治疗: ",
    "Duration: ": "持续时间: ",
    "Bonus: ": "奖励: ",
    "Chances to block: ": "格挡几率: ",
    "Gold dropped: ": "黄金掉落: ",
    "Extra Slots: ": "额外插槽: ",
    "Type: ": "类型: ",
    "Quill Rat died. Xp earned: ": "毛老鼠死了。获得经验：",
    "You have been killed by Zombie. Xp lost: ": "你被僵尸杀死了。 经验丢失：",
    "Fallen: Hit ": "堕落者：命中",
    "Quill Rat: Hit ": "毛老鼠：命中",
    "You: Hit ": "你：命中",
    "Zombie: Hit ": "僵尸：命中",
    "Zombie: 僵尸 ": "你：命中",
    "Zombie died. Xp earned: ": "僵尸死了。 获得经验：",
    "Attack rating: ": "攻击率：",
    "Level required: ": "要求等级：",
    "Required strength: ": "力量要求：",
    "Unlocked: ": "解锁：",
    "Shrine of Resist Fire ": "火抗神殿",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " (Normal)": " (普通)",
    " (Slow)": " (慢)",
    " (Fast)": " (快)",
    " (Very fast)": " (很快)",
    " (Very slow)": " (很慢)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)s\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) \(chance to hit: ([\d\.]+)\%\)$/, '$1（命中率：$2%）'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Reward: (.+) Skill point$/, '奖励：$1 技能点'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);