/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "(physical)": "(物理)",
    "Attack rating": "攻击率",
    "Attack speed": "攻击速度",
    "Attributes": "属性",
    "Cast rate": "施放率",
    "Chances to block": "格挡几率",
    "Cold": "寒冷",
    "Damage": "伤害",
    "Damage reduction": "减少伤害",
    "Defense": "防御",
    "Dexterity": "灵巧",
    "Donate": "捐赠",
    "Energy": "能量",
    "Explore the Blood Moor to begin your adventure.": "探索血之沼泽开始你的冒险。",
    "Fire": "火",
    "Freeze duration": "冻结时间",
    "Get back to the camp to get healed !": "回到营地接受治疗！",
    "Got it !": "知道了！",
    "Increase chances to find magical": "增加找到魔法的机会",
    "Increase defense and attack rating": "提高防御和攻击率",
    "Levels": "等级",
    "Life": "生命值",
    "Lightning": "闪电",
    "Magical Damage reduction": "魔法伤害减免",
    "Mana": "法力",
    "Open Inventory": "打开仓库",
    "Options": "选项",
    "Other data": "其他数据",
    "Poison": "毒",
    "Poison duration": "中毒持续时间",
    "Quests": "任务",
    "Resistances": "抗性",
    "Rogue Encampment (H)": "盗贼营地 (H)",
    "Show Gold": "显示金子",
    "Show hits": "显示命中",
    "Show kills": "显示击杀",
    "Show Non-magical items": "显示非魔法物品",
    "Skills": "技能",
    "Stats": "统计",
    "Strength": "力量",
    "Stun duration": "眩晕时间",
    "Support & Credits": "支持和积分",
    "Vitality": "体力",
    "Your life is low.": "你的生命值很低。",
    "All": "全部",
    "Body": "身体",
    "Body:": "身体：",
    "Equipment": "装备",
    "Feet": "脚",
    "Feet:": "脚：",
    "Finger": "手指",
    "Finger:": "手指：",
    "Gold:": "金子：",
    "Hands": "手",
    "Hands:": "手：",
    "Head": "头",
    "Head:": "头：",
    "Inventory": "仓库",
    "Neck": "脖子",
    "Neck:": "脖子：",
    "Nothing": "无",
    "Potions": "药水",
    "Shield": "盾",
    "Shield:": "盾：",
    "Show:": "显示：",
    "Waist": "腰部",
    "Waist:": "腰部：",
    "Weapon": "武器",
    "Weapon:": "武器：",
    "Auto-pause on inventory": "打开仓库时自动暂停",
    "Clear the Den of Evil": "清除邪恶的巢穴",
    "Close": "关闭",
    "Combat": "战斗",
    "Dark mode": "深色模式",
    "Death:": "死亡：",
    "Den of Evil": "邪恶巢穴",
    "Discipline": "惩罚",
    "Download": "下载",
    "Export / Import": "导入/导出",
    "Hard reset": "硬重置",
    "Increase damages": "增加伤害",
    "Killed:": "击杀：",
    "Light mode": "浅色模式",
    "Magic": "魔法",
    "Magic Missile": "魔法飞弹",
    "Parry": "格挡",
    "Restore life": "恢复生命",
    "Shock": "冲击",
    "Summon Crow": "召唤乌鸦",
    "Quill Rat": "毛老鼠",
    "Staff": "手杖",
    "+1 to Cold Mastery (Sorceress only)": "+1 冰冷精通（仅限女术士）",
    "Drink": "喝",
    "Equip": "装备",
    "Fallen": "堕落者",
    "Get back to the camp when your life is too low.": "当你的生命值太低时回到营地。",
    "Item dropped:": "掉落物品：",
    "Minor healing potion": "小型治疗药水",
    "Potion dropped: Minor healing potion": "掉落的药水：小型治疗药水",
    "Sell": "出售",
    "Short Staff": "短杖",
    "Two-handed": "双手",
    "Unlocked: Potion quickslots": "解锁：药水快速槽",
    "(magical)": "(魔法)",
    "(normal)": "(普通)",
    "Minor mana potion": "小法力药水",
    "Zombie": "僵尸",
    "Leather Boots": "皮靴",
    "Undead": "不死",
    "Unequip": "卸下",
    "[passive] Increase damages.": "[被动] 增加伤害。",
    "Current level:": "当前等级：",
    "Create a wave of electrical energy that deals damage and has 25% chances to stun all monsters around.": "制造一道造成伤害的电能波，并有 25% 的几率击晕周围的所有怪物。",
    "Heal.": "治疗.",
    "Increase block rate.": "提高格挡几率。",
    "Increase life & life regeneration": "提高 生命值 和 生命值恢复",
    "Launch a magic missile, dealing magical damage to 1 monster.": "发射魔法飞弹，对1只怪物造成魔法伤害。",
    "+1 Skill quickslot": "+1 快捷技能槽",
    "Summon a crow to fight for you.": "召唤乌鸦为你而战。",
    "Next level:": "下一级：",
    "Increase mana & mana regeneration": "增加法力和法力恢复",
    "+75% to resist fire for 120s": "+75% 火抗，持续 120 秒",
    "Buckler": "小圆盾",
    "Dagger": "匕首",
    "Leather Gloves": "皮手套",
    "equipped": "已装备",
    "Sash": "腰带",
    "Bronze Hand Axe": "青铜手斧",
    "Robe": "长袍",
    "Short Sword": "短剑",
    "Den of Evil": "邪恶巢穴",
    "Level up !": "升级了！",
    "+1 to Carrion Vine (Druid only)": "+1 腐肉藤蔓（仅限德鲁伊）",
    "+1 to Meteor (Sorceress only)": "+1 流星（仅限女术士）",
    "Adventurer only": "仅限冒险家",
    "Axe": "斧子",
    "Druid only": "仅限德鲁伊",
    "Fallen Shaman": "堕落萨满",
    "Gargantuan Beast": "巨兽",
    "Hand Axe": "手斧",
    "Lightning enchanted monsters will deal lightning damage every time they get hit!": "被闪电强化的怪物每次被击中都会造成闪电伤害！",
    "Sword": "剑",
    "Summon Fallen": "召唤堕落者",
    "This monster is special. It deals elemental damages. Try to increase your resistances to avoid being crushed.": "这个怪物很特别。 它会造成元素伤害。 尝试增加你的抵抗力以避免被压碎。",
    "+50% damage to undeads": "+50% 对不死生物的伤害",
    "(rare)": "(稀有)",
    "Club": "击棍",
    "Bronze Ring": "青铜戒指",
    "Azure Hard Leather Armor of Strength": "青色硬皮力量盔甲",
    "Epic": "史诗",
    "Gamble": "赌博",
    "Get reward": "领取奖励",
    "Gheed": "吉德",
    "Kashya": "卡夏",
    "Kill Blood Raven in the Burial's Grounds": "在墓地杀死血鸦",
    "Leather Armor of Jackal": "豺狼皮甲",
    "Legendary": "传奇",
    "Lizard's Quilted Armor of Remedy": "蜥蜴的绗缝护甲",
    "Mace": "钉头锤",
    "Magical": "魔法",
    "Market": "市场",
    "Merchant": "商人",
    "Meshif": "梅西夫",
    "Price": "价格",
    "Rare": "稀有",
    "Show more": "显示更多",
    "Sisters' Burial Grounds": "姐妹墓地",
    "Warriv": "瓦里夫",
    "Wolf Head": "狼头",
    "[passive] Increase damages and attack rating when using Axes.": "[被动]使用斧头时增加伤害和攻击等级。",
    "[passive] Increase damages and attack rating when using Maces.": "[被动] 使用钉头锤时增加伤害和攻击等级。",
    "[passive] Increase damages and attack rating when using Swords.": "[被动]使用剑时增加伤害和攻击等级。",
    "[passive] Increase defense.": "[被动] 增加防御。",
    "[passive] Increase resistances to all elements.": "[被动] 增加对所有元素的抗性。",
    "+1 to Fireball (Sorceress only)": "+1 火球术（仅限女术士）",
    "+1 to Summon Wolf (Druid only)": "+1 召唤狼（仅限德鲁伊）",
    "5% life stolen per hit": "每次命中偷走 5% 生命",
    "Accurate": "精准",
    "Agile": "灵巧",
    "Amulet of Strength": "力量护身符",
    "Axe mastery": "斧头精通",
    "Azure Buckler": "蔚蓝圆盾",
    "Azure Heavy Boots": "碧蓝重靴",
    "Azure Leather Armor": "蔚蓝皮甲",
    "Azure Leather Gloves": "天蓝色皮手套",
    "Bash": "重击",
    "Beryl Leather Boots": "绿柱石皮靴",
    "Bronze Short Sword": "青铜短剑",
    "Bronze Spiked Club": "青铜尖刺击棍",
    "Bronze Spiked Club of Readiness": "青铜尖刺击棍",
    "Brutal": "野蛮",
    "Buckler of Blocking": "格挡圆盾",
    "Buckler of Dexterity": "灵巧圆盾",
    "Burning Skull Cap": "燃烧骷髅帽",
    "Cap": "帽",
    "Change class": "更换职业",
    "Chilling Helm": "冰冷头盔",
    "Club of Worth": "价值击棍",
    "Concentrate": "集中",
    "Crimson Robe of Dexterity": "深红灵巧长袍",
    "Dagger of Craftsmanship": "工艺匕首",
    "Dagger of Worth": "价值匕首",
    "Expert's Club": "专家击棍",
    "Expert's Hand Axe of Worth": "专家手斧",
    "Expert's Short Sword of Slaying": "专家的杀戮短剑",
    "Fast": "快速",
    "Fiery Dagger": "炽热匕首",
    "Fiery Spiked Club": "火热的尖刺击棍",
    "Fights beside you": "战斗时在你身边",
    "Frenzy": "疯狂",
    "Gives you potions when you need them": "在你需要的时候给你药水",
    "Gwinni (Fighter)": "格温妮（战士）",
    "Hard Leather Armor": "硬皮盔甲",
    "Hard Leather Armor of Strength": "硬皮力量盔甲",
    "Heavy Boots": "重型靴子",
    "Heavy Boots of Chance": "机会重靴",
    "Heavy Gloves of Bat": "蝙蝠重手套",
    "Hire": "雇佣",
    "Hirelings": "雇佣",
    "Increase damages and 25% chances to stun monster for a short period.": "增加伤害和 25% 几率在短时间内击晕怪物。",
    "Increase damages and attack rating.": "增加伤害和攻击等级。",
    "Increase damages, attack rating and attack speed.": "增加伤害、攻击等级和攻击速度。",
    "Iron Scimitar": "铁弯刀",
    "Iron Skin": "铁皮",
    "Isolde (Fighter)": "伊索尔德（战士）",
    "Isolde (Seller)": "伊索尔德（卖家）",
    "Ithera (Assistant)": "伊瑟拉（助理）",
    "Jagged Axe": "锯齿斧",
    "Jagged Club of Quality": "优质的锯齿击棍",
    "Jagged Dagger": "锯齿匕首",
    "Jagged Hand Axe": "锯齿手斧",
    "Jagged Sabre": "锯齿军刀",
    "Jagged Scimitar": "锯齿弯刀",
    "Jemali (Fighter)": "杰马利（战斗机）",
    "Kill the Countess": "杀死伯爵夫人",
    "Leather Armor": "皮甲",
    "Leather Armor of Dexterity": "灵巧皮甲",
    "Leather Armor of Remedy": "治疗皮甲",
    "Leather Boots of Fox": "狐狸皮靴",
    "Leather Gloves of Dexterity": "灵巧皮手套",
    "Leather Gloves of Jackal": "豺狼皮手套",
    "Leather Gloves of Renewal": "再生皮手套",
    "Leharas (Seller)": "莱哈拉斯 (Celler)",
    "Light Belt": "光带",
    "Lizard's Leather Boots": "蜥蜴皮靴",
    "Lizard's Ring": "蜥蜴之戒",
    "Lizard's Robe": "蜥蜴长袍",
    "Lizard's Small Shield": "蜥蜴的小盾",
    "Mace mastery": "狼牙棒精通",
    "Mahala (Fighter)": "玛哈拉（战士）",
    "Masteries": "天赋",
    "Mercenary": "雇佣兵",
    "Natural Resistance": "自然抗性",
    "Precise": "精准",
    "Quilted Armor": "绗缝盔甲",
    "Reward: xp bonus": "奖励：经验奖励",
    "Ring of Craftsmanship": "工艺之戒",
    "Robe of Dexterity": "灵巧长袍",
    "Robe of Fox": "狐狸长袍",
    "Robe of Strength": "力量长袍",
    "Sash of Dexterity": "灵巧腰带",
    "Scimitar": "弯刀",
    "Scimitar of Craftsmanship": "工艺弯刀",
    "Scimitar of Worth": "价值弯刀",
    "Self-healing": "自我治疗",
    "Sells your junk items for you": "为您出售您的垃圾物品",
    "Septic Club": "腐烂的击棍",
    "Septic Large Axe": "腐烂的大斧",
    "Shivering Hand Axe": "颤抖的手斧",
    "Short Staff of Craftsmanship": "手工艺短杖",
    "Short Sword of Worth": "价值短剑",
    "Silver Spiked Club": "银色尖刺击棍",
    "Skull Cap of Remedy": "骷髅头帽",
    "Small Shield": "小盾",
    "Small Shield of Blocking": "小格挡之盾",
    "Snake's Cap": "蛇帽",
    "Snake's Leather Armor": "蛇的皮甲",
    "Snake's Wolf Head": "蛇的狼头",
    "Snowy Dagger of Worth": "白雪皑皑的价值匕首",
    "Snowy Short Sword": "雪域短剑",
    "Spiked Club": "尖刺击棍",
    "Static Club": "静态击棍",
    "Static Spiked Club": "静态尖刺击棍",
    "Strong Wolf Head": "强壮的狼头",
    "Sword mastery": "剑道精通",
    "Tangerine Leather Boots": "橘色皮靴",
    "Thawing Potion": "解冻药水",
    "The Forgotten Tower": "被遗忘的塔",
    "Tough": "坚韧",
    "- Extra strong": "- 超强",
    "Antidote": "解毒剂",
    "Blood Clan": "血族",
    "Dark Ranger": "黑暗游侠",
    "Fire enchanted": "火焰强化",
    "Ghost": "鬼魂",
    "Long Staff": "长杖",
    "No available skill": "没有可用的技能",
    "Shortcut:": "捷径：",
    "The Countess": "伯爵夫人",
    "Undead - Mana burn": "不死族——法力燃烧",
    "Brute": "野蛮人",
    "Carver": "利刃魔",
    "Carver Shaman": "利刃魔萨满",
    "Dismiss": "解雇",
    "Enabled": "启用",
    "Give": "给予",
    "Hawk Helm": "鹰头盔",
    "Mana potion": "法力药水",
    "Iron Hand Axe": "铁手斧",
    "Healing potion": "治疗药水",
    "Night Clan": "夜族",
    "Skeleton Archer": "骷髅弓箭手",
    "Returned": "回归者",
    "Strong": "强壮",
    "Summon Carver": "召唤利刃魔",
    "Thawing potion": "解冻药水",
    "when life is under": "当生命值低于",
    "+1 to Cold skills (sorceress only)": "+1 冰冷技能（仅限女术士）",
    "+1 to Fire Mastery (Sorceress only)": "+1 火焰精通（仅限女术士）",
    "+1 to Fire skills (sorceress only)": "+1 火焰技能（仅限女术士）",
    "+1 to Frozen Orb (Sorceress only)": "+1 冰冻宝珠（仅限女术士）",
    "+1 to Mana freeze (Sorceress only)": "+1 法力冻结（仅限女术士）",
    "+1 to Masteries (barbarian only)": "+1 精通（仅限野蛮人）",
    "+1 to Summon Mastery (Druid only)": "+1 召唤精通（仅限德鲁伊）",
    "+1 to Summon Pixie (Druid only)": "+1 召唤小精灵（仅限德鲁伊）",
    "+1 to Werebear (Druid only)": "+1 熊人（仅限德鲁伊）",
    "Add 2 poison damage over 2 seconds": "在 2 秒内增加 2 点毒伤害",
    "Cure from poison": "从毒中治愈",
    "Large Axe": "大斧",
    "Done !": "完成！",
    "Kill Andariel": "杀死 安达利尔",
    "Kill Duriel": "杀死 杜瑞尔",
    "Kill Mephisto": "杀死 墨菲斯托",
    "Reward: -1 monster / level in Act I": "奖励：第一幕中的-1 怪物/等级",
    "Reward: -1 monster / level in Act I & II": "奖励：第一幕和第二幕中的-1 怪物/等级",
    "Reward: -1 monster / level in Act I, II & III": "奖励：第一、二、三幕中的怪物/等级-1",
    "Reward: Auto-skip to next level (act I)": "奖励：自动跳到下一个级别（第一幕）",
    "Reward: Auto-skip to next level (act II)": "奖励：自动跳到下一个级别（第二幕）",
    "Reward: Relic effect +25%": "奖励：遗物效果+25%",
    "Reward: Start with a dagger": "奖励：从匕首开始",
    "Reward: Start with a poignard": "奖励：从一个 匕首 开始",
    "Reward: Start with a quilted armor": "奖励：从一件绗缝盔甲开始",
    "Use 10,000 skills in one run": "一轮游戏里使用 10,000 个技能",
    "Beryl Leather Gloves": "绿柱石皮手套",
    "Dark Hunter": "黑暗猎人",
    "Hungry Dead": "饿死鬼",
    "Moon Clan": "月族",
    "Show less": "显示更少",
    "Skeleton": "骷髅",
    "+1 to Frozen Armor (Sorceress only)": "+1 冰冻护甲（仅限女术士）",
    "+1 to Heat (Sorceress only)": "+1 加热（仅限女术士）",
    "+1 to Lycanthropy (Druid only)": "+1 变狼术（仅限德鲁伊）",
    "13% better chance of getting magic items": "获得魔法物品的几率提高 13%",
    "3% mana stolen per hit": "每次击中 3% 法力椅子",
    "5% Faster block rate": "5% 更快的格挡率",
    "Club of Craftsmanship": "手工艺俱乐部",
    "Dagger of Bat": "蝙蝠匕首",
    "Unlock 1 class": "解锁 1 职业",
    "Adventurer": "冒险家",
    "Azrael": "阿兹瑞尔",
    "Barbarian": "野蛮人",
    "Basanti": "巴桑蒂",
    "Can auto-cast 1 spell.": "可以自动施放 1个 法术。",
    "Class requirements (other than class & level) are needed only the first time you unlock a class.": "职业需求(除了职业和等级)只在你第一次解锁一个职业时才需要。",
    "Class selection": "职业选择",
    "Class unlocked": "职业解锁",
    "Devilkin": "恶魔人",
    "Druid": "德鲁伊",
    "Gain +15 to energy.": "获得 +15 能量。",
    "Gain +15 to vitality.": "获得 +15 生命力。",
    "Hannah": "汉娜",
    "Klaudia": "克劳迪娅",
    "Kyle": "凯尔",
    "Neeraj": "尼拉吉",
    "No requirements": "无要求",
    "Poison & Cold resist +15.": "毒&寒冷抗性+15。",
    "Raissa": "赖萨",
    "Requirements:": "要求：",
    "Select": "选择",
    "Sorceress": "女术士",
    "Specialize in combat.": "专攻格斗。",
    "Specialize in Magic.": "专攻魔法。",
    "Specialize in Summons & transformation.": "专注于召唤和转变。",
    "Starting class.": "初始职业。",
    "(epic)": "(史诗)",
    "(legendary)": "(传奇)",
    "+1 to Werewolf (Druid only)": "+1 狼人（仅限德鲁伊）",
    "when mana is under": "当法力低于",
    "Lightning enchanted": "闪电强化",
    "Septic Short Staff of Readiness": "蓄势待发的腐烂短杖",
    "- Undead": "- 不死",
    "Corpsefire": "尸火",
    "Azure Robe": "碧蓝长袍",
    "Cold enchanted": "寒冷强化",
    "Coldcrow": "寒鸦",
    "Crimson Leather Boots of Chance": "深红皮靴之几率",
    "Crimson Leather Gloves": "深红色皮手套",
    "Fanatic Cap of Jackal": "狂热的豺狼帽",
    "Hand Axe of Worth": "价值手斧",
    "Iron Short Sword": "铁短剑",
    "Iron Spiked Club of Slaying": "铁刺杀戮击棍",
    "Lizard's Cap": "蜥蜴帽",
    "Ring of Renewal": "复兴之戒",
    "Septic Spiked Club of Craftsmanship": "腐败的尖刺手工击棍",
    "Short Staff of Worth": "物有所值的短杖",
    "Snowy Dagger": "雪之匕首",
    "Spiked Club of Bat": "蝙蝠尖刺击棍",
    "Steel Axe": "钢斧",
    "Sturdy Quilted Armo": "坚固的绗缝盔甲",
    "Vile Hunter": "邪恶猎人",
    "Annor": "安诺",
    "Blaise": "布莱斯",
    "Chalan": "查兰",
    "Debi": "德比",
    "Gulzar": "古尔扎",
    "Leather Armor of Strength": "力量皮甲",
    "Maeko": "前子",
    "Sturdy Quilted Armor": "坚固的绗缝盔甲",
    "3% life stolen per hit": "每次命中偷取 3% 生命",
    "Misshapen": "异形",
    "Abhaya": "阿巴亚",
    "Akara": "阿卡拉",
    "All (including uniques)": "全部（包括唯一性）",
    "Clear Tristram": "清除 崔斯特瑞姆",
    "Dark Wood": "黑暗森林",
    "Elzix": "埃尔齐克斯",
    "Emilio": "埃米利奥",
    "Epic and below": "史诗及以下",
    "Expert's Axe of Leech": "专家的水蛭斧",
    "Expert's Skull Cap": "专家骷髅帽",
    "Iantha": "扬莎",
    "items with value below": "物品价值低于",
    "Leather Gloves of Regeneration": "再生皮手套",
    "Legendary and below": "传奇及以下",
    "Lizard's Leather Boots of Jackal": "蜥蜴的豺狼皮靴",
    "Magical and below": "神奇及以下",
    "Mahala": "马哈拉",
    "Normal": "普通的",
    "Olena": "埃琳娜",
    "Rare and below": "稀有及以下",
    "Resplenish life +3%": "补充生命 +3%",
    "Ring of Worth": "价值之戒",
    "Search for Cain": "寻找该隐",
    "Selling every 5.0s.": "每 5.0 秒销售一次。",
    "Smoldering Large Axe of Readiness": "闷烧的准备大斧",
    "Static Two-Handed Sword": "静态双手剑",
    "Strong Hard Leather Armor": "坚固的硬皮甲",
    "Strong Sash": "强力腰带",
    "Unfreeze": "解冻",
    "Visala": "维萨拉",
    "You": "你",
    "Add 4 poison damage over 2 seconds": "在 2 秒内增加 4 点毒伤害",
    "Spike Fiend": "刺魔",
    "Extra strong": "超强",
    "Pupil Amulet": "学生护身符",
    "Short Staff of Measure": "测量短杖",
    "Treehead Woodfist": "树头木拳",
    "Tristram": "崔斯特瑞姆",
    "- Extra strong - Undead": "- 超强 - 不死族",
    "Griswold": "格里斯沃尔德",
    "Spiked Shield of Fox": "狐狸尖刺盾",
    "Russet Leather Gloves": "赤褐色皮革手套",
    "Glowing Scimitar": "炽热弯刀",
    "Fanatic Hand Axe": "狂热手斧",
    "Forgotten Tower": "遗忘之塔",
    "Long Staff of Leech": "水蛭长杖",
    "The Hole": "洞窟",
    "Tamoe Highland": "泰摩高地",
    "Returned Mage": "回归法师",
    "Dark Stalker": "黑暗猎手",
    "Vile Archer": "邪恶弓箭手",
    "Thorn Beast": "荆棘兽",
    "The Pit": "深渊",
    "Vikhyat": "维克亚特",
    "+1 to Magic skills (apprentice only)": "+1 魔法技能（仅限学徒）",
    "+1 to Summon Resist (Druid only)": "+1 召唤抗性（仅限德鲁伊）",
    "14% Faster block rate": "14% 更快的阻止率",
    "Amulet of Craftsmanship": "工艺护身符",
    "Amulet of Jackal": "豺狼护身符",
    "Beryl Small Shield": "绿柱石小盾",
    "Cap of Jackal": "豺狼帽",
    "Chain Gloves of Fox": "狐狸链手套",
    "Clear the Barracks": "清除军营",
    "Crimson Buckler of Deflecting": "偏转的深红圆盾",
    "Crimson Sash of Fox": "深红狐狸腰带",
    "Durga": "杜尔加",
    "Expert's Large Axe": "专家的大斧",
    "Fara": "危险",
    "Fiery Short Sword": "炽热短剑",
    "Glowing Large Axe": "发光的大斧",
    "Helm": "战法之盔",
    "Jagged Club of Craftsmanship": "锯齿状工艺俱乐部",
    "Jagged Spiked Club": "锯齿尖刺俱乐部",
    "Jerhyn": "杰海因",
    "Learner's Ring": "学习者戒指",
    "Leharas": "莱哈拉的",
    "Level": "等级",
    "Liene": "留置权",
    "Returned Archer": "回归弓箭手",
    "Reward: Ability to imbue an item": "奖励：灌输物品的能力",
    "Ring Mail of Warding": "病房呼叫邮件",
    "Ring of Dexterity": "灵巧之戒",
    "Sabre": "军刀",
    "Sash of Regeneration": "再生腰带",
    "Septic Scimitar of Craftsmanship": "工艺的化粪弯刀",
    "Septic Short Staff": "腐烂的短杖",
    "Skull Cap of Skill": "技能之骷髅帽",
    "Snake's Leather Armor of Strength": "蛇的力量皮甲",
    "Snake's Sash of Strength": "蛇的力量腰带",
    "Speed": "速度",
    "Stash": "藏匿",
    "Steel Mace": "钢锤",
    "Store": "存放",
    "Sturdy Cap": "坚固的帽子",
    "Take": "拿走",
    "Tangerine Heavy Boots of Strength": "橘红色力量之靴",
    "Tangerine Ring Mail of Jackal": "豺狼橘环甲",
    "Tangerine Wolf Head": "橘色狼头",
    "Tools of the Trade": "贸易工具",
    "Vikhyat: Level up !": "维克亚特：升级！",
    "Wendy": "温迪",
    "(Fighter)": "(战士)",
    "Dark Archer": "黑暗射手",
    "Light mana potion": "光魔药水",
    "Monastery Gate": "修道院大门",
    "Studded Leather": "铆钉皮革",
    "Disfigured": "毁容者",
    "(unique Belt)": "（独特的腰带）",
    "[passive] Increase summons life and defense.": "[被动] 增加召唤物生命和防御。",
    "[passive] Increase summons resistances to all elements.": "[被动] 增加对所有元素的召唤抗性。",
    "[passive] Increases the Life of the Druid while Shapeshifted, as well as the duration of the transformation.": "[被动] 增加变形时德鲁伊的生命，以及变形的持续时间。",
    "+1 to Combat skills (barbarian only)": "+1 战斗技能（仅限野蛮人）",
    "Add 50 poison damage over 10 seconds": "在 10 秒内增加 50 点毒伤害",
    "Azure Light Belt of Fox": "碧蓝狐狸腰带",
    "Azure Wolf Head of Dexterity": "青狼灵巧之首",
    "Beryl Small Shield of Steadiness": "绿柱石小稳固盾",
    "Beryl Wolf Head": "绿柱石狼头",
    "Carrion Vine": "腐肉藤",
    "Create item": "创建物品",
    "Crimson Ring of Apprentice": "深红学徒之戒",
    "Failed to create item": "创建物品失败",
    "Fanatic Axe of Craftsmanship": "狂热的手工艺之斧",
    "Freezing": "冻结",
    "Half stun duration": "半眩晕时间",
    "Item succesfully created:": "物品成功创建：",
    "Kasim": "卡西姆",
    "Lapis Hard Leather Armor of Skill": "青金石硬皮技能护甲",
    "Learner's Skull Cap of Steadiness": "学习者稳定骷髅帽",
    "Level  1 - Damage reduced by 0": "等级 1 - 伤害减少 0",
    "Level  5 - Life and mana regneration +0%": "5级 - 生命和法力回复 +0%",
    "Level 10 - Chances to freeze on hit: 0%": "10 级 - 击中时冻结的几率：0%",
    "Level 15 - All resistances +0": "15级 - 所有抗性+0",
    "Level 20 - Damage +0%": "20 级 - 伤害 +0%",
    "Level 25 - Attack rating +0%": "25 级 - 攻击等级 +0%",
    "Level 30 - Attack speed +0%.": "30 级 - 攻击速度 +0%。",
    "Liaza": "利亚萨",
    "Look! You can now select a new class.": "看！您现在可以选择一个新职业。",
    "Lycanthropy": "狼人",
    "Shape Shifting": "形态变换",
    "Shards": "碎片",
    "Shards:": "碎片：",
    "Shimmering Ring of Strength": "闪光的力量之戒",
    "Snake's Amulet of Leech": "蛇的水蛭护身符",
    "Strong Heavy Gloves of Dexterity": "坚固的重型灵巧手套",
    "Summon a eat corpses to heal you and your party.": "召唤一个吃尸体来治愈你和你的队伍。",
    "Summon a pixie that gives powers to you and all your summons depending on levels.": "召唤一个小精灵，根据等级赋予你和你所有的召唤力量。",
    "Summon a wolf to fight for you.": "召唤一只狼为你而战。",
    "Summon Mastery": "召唤精通",
    "Summon Pixie": "召唤小精灵",
    "Summon Resist": "召唤抵抗",
    "Summon Wolf": "召唤狼",
    "Summons": "召唤",
    "Transform into a bear.": "变身熊。",
    "Transform into a wolf.": "变身狼。",
    "Trollskin": "巨魔皮",
    "Tylena": "泰莱娜",
    "Werebear": "熊人",
    "Werewolf": "狼人",
    "You can now exile to get relics which makes you gather xp faster.": "您现在可以流放以获取使您更快地收集经验的遗物。",
    "You can now get hirelings to help you fight or to assist you in menial tasks.": "您现在可以雇佣雇佣兵来帮助您战斗或协助您完成琐碎的任务。",
    "You can try to create a unique item with your shards": "您可以尝试使用您的碎片创建一个独特的物品",
    "(-10 from Act III)": "（第三幕 -10）",
    "[passive] Increase mana regeneration.": "[被动] 增加法力回复。",
    "[passive] Reduce mana cost of all spells.": "[被动] 降低所有法术的法力消耗。",
    "A pulsating orb that deals cold damage to all monsters around.": "一个脉动的球体，对周围的所有怪物造成冰冷伤害。",
    "Act I": "第一幕",
    "Act II": "第二幕",
    "Act III": "第三幕",
    "Clear Travincal": "清除 崔凡克城",
    "Cold Mastery": "寒冷精通",
    "Create an armor that absorbs damage.": "创造一个可以吸收伤害的盔甲。",
    "Fire Mastery": "火焰精通",
    "Fireball": "火球",
    "Frozen Armor": "冰冻盔甲",
    "Frozen Orb": "冰冻宝珠",
    "Heat": "热量",
    "Increase efficiency of active cold spells for every cast (permanent).": "提高每次施法的主动寒冷法术的效率（永久）。",
    "Increase efficiency of active fire spells for every cast (permanent).": "提高每次施法的主动火焰法术的效率（永久）。",
    "Launch a fire ball, dealing fire damage to all monsters around.": "发射一个火球，对周围所有怪物造成火焰伤害。",
    "Launch meteors at your enemies, dealing fire damage to all monsters around during a period.": "向你的敌人发射流星，在一段时间内对周围的所有怪物造成火焰伤害。",
    "Mana freeze": "法力冻结",
    "Meteor": "流星",
    "Ruined Fane": "毁坏的神殿",
    "The Blackened Temple": "黑化的神殿",
    "Hell Cat": "地狱猫",
    "Yeti": "雪人",
    "Preserved Dead": "蜡化木乃伊",
    "Steel Scarab": "钢铁圣甲虫",
    "Ghoul Lord": "食尸鬼领主",
    "Apparition": "幻影",
    "- Extra strong - Extra fast": "- 超强 - 超快",
    "Ancient Tunnels": "古代隧道",
    "Andariel": "安达利尔",
    "Arachnid Lair": "蛛形纲动物巢穴",
    "Arcane Sanctuary": "奥术圣域",
    "Auto-cast": "自动施法",
    "Banished": "被流放",
    "Barracks": "兵营",
    "Bone Mage": "骨法师",
    "Canyon of the Magi": "魔法师峡谷",
    "Catacombs": "地下墓穴",
    "Cathedral": "大教堂",
    "Claw Viper Temple": "爪蝰蛇神庙",
    "Dark One": "黑暗者",
    "Dark Shaman": "黑暗萨满",
    "Death Clan": "死亡部落",
    "Disused Fane": "废弃的神殿",
    "Disused Reliquary": "废弃的圣物箱",
    "Dry Hills": "干山",
    "Far Oasis": "远绿洲",
    "Flayer Dungeon": "剥皮地牢",
    "Flayer Jungle": "剥皮者丛林",
    "Forgotten Reliquary": "被遗忘的圣物箱",
    "Forgotten Temple": "被遗忘的寺庙",
    "Ghoul": "食尸鬼",
    "Gorebelly": "血肚",
    "Great Marsh": "大沼泽",
    "Halls of the Dead": "死者大厅",
    "Harem": "后宫",
    "Hazade": "阴霾",
    "Ilzan": "伊尔赞",
    "Inner Cloister": "内部回廊",
    "Iron Club": "铁杆俱乐部",
    "Iron Ring of Slaying": "杀戮之铁环",
    "Ithera": "伊瑟拉",
    "Jail": "监狱",
    "Kurast Bazaar": "库拉斯特集市",
    "Kurast Causeway": "库拉斯特堤道",
    "Lost City": "失落之城",
    "Lower Kurast": "下库拉斯特",
    "Maggot Lair": "蛆虫巢穴",
    "Ocher Buckler": "赭色圆环",
    "Outer Cloister": "外院",
    "Palace Cellar": "皇宫酒窖",
    "Poison enchanted": "毒附魔",
    "Razor Spine": "剃刀脊椎",
    "Resurrect (": "复活（",
    "Rocky Waste": "岩石废物",
    "Ruined Temple": "破庙",
    "Sewers": "下水道",
    "Shimmering Cap": "闪光帽",
    "Spider Cavern": "蜘蛛洞",
    "Spider Forest": "蜘蛛森林",
    "Stony Tomb": "石墓",
    "Stun Attack - Area attack": "眩晕攻击 - 区域攻击",
    "Summon Dark One": "召唤黑暗一号",
    "Swampy Pit": "沼泽坑",
    "Tal Rashas Tomb": "塔拉沙斯墓",
    "Tangerine Leather Boots of Fortune": "橘皮财富之靴",
    "The Smith": "史密斯",
    "Undead - Area attack": "亡灵 - 区域攻击",
    "Undead - Summon Horror": "亡灵 - 召唤恐怖",
    "Unraveler": "解开器",
    "Upper Kurast": "上库拉斯特",
    "Wraith": "幽灵",
    "(cold)": "(寒冷)",
    "(Dead)": "(死亡)",
    "Freeze enemy for 1 seconds": "冻结敌人1秒",
    "(unique Amulet)": "（独特的护身符）",
    "(unique Ring)": "（独特的戒指）",
    "(unique War Hammer)": "（独特的战锤）",
    "+1 to all skills": "+1 所有技能",
    "+1 to barbarian skills level": "+1 野蛮人技能等级",
    "+2 to Carrion Vine (Druid only)": "+2 腐肉藤蔓（仅限德鲁伊）",
    "+2 to Cold Mastery (Sorceress only)": "+2 冰冷精通（仅限女术士）",
    "+2 to Cold skills (sorceress only)": "+2 冰冷技能（仅限女术士）",
    "+2 to Fire skills (sorceress only)": "+2 火焰技能（仅限女术士）",
    "+2 to Fireball (Sorceress only)": "+2 火球术（仅限女术士）",
    "+2 to Frozen Orb (Sorceress only)": "+2 冰冻宝珠（仅限女术士）",
    "+2 to Lycanthropy (Druid only)": "+2 变狼术（仅限德鲁伊）",
    "+2 to Mana freeze (Sorceress only)": "+2 法力冻结（仅限女术士）",
    "+2 to Meteor (Sorceress only)": "+2 流星（仅限女术士）",
    "+2 to Shape Shifting skills (druid only)": "+2 变形技能（仅限德鲁伊）",
    "+2 to Summon Mastery (Druid only)": "+2 召唤精通（仅限德鲁伊）",
    "+2 to Summon Pixie (Druid only)": "+2 召唤小精灵（仅限德鲁伊）",
    "+2 to Werebear (Druid only)": "+2 熊人（仅限德鲁伊）",
    "+3 to Carrion Vine (Druid only)": "+3 腐肉藤蔓（仅限德鲁伊）",
    "+3 to Cold skills (sorceress only)": "+3 冰冷技能（仅限女术士）",
    "+3 to Fireball (Sorceress only)": "+3 火球术（仅限女术士）",
    "+3 to Mana freeze (Sorceress only)": "+3 法力冻结（仅限女术士）",
    "+3 to Meteor (Sorceress only)": "+3 流星（仅限女术士）",
    "+3 to Summon Wolf (Druid only)": "+3 召唤狼（仅限德鲁伊）",
    "+3 to Werewolf (Druid only)": "+3 狼人（仅限德鲁伊）",
    "Add 9 poison damage over 3 seconds": "在 3 秒内增加 9 点毒伤害",
    "Amber Falcon Mask of Wolf": "狼的琥珀猎鹰面具",
    "Antlers of Ox": "牛角",
    "Beryl Heavy Boots of Gifted": "Beryl Heavy Boots of Gifted",
    "Beryl Heavy Gloves of Thawing": "绿柱石重度解冻手套",
    "Blazing Jo Staff": "炽热的乔法杖",
    "Blazing Long Staff of Alacrity": "炽热长法杖",
    "Boreal War Staff of Locust": "蝗虫的北方战争法杖",
    "Damage Reduced by 1": "伤害减少 1",
    "Duriel's Ring": "杜瑞尔之戒",
    "Feral Spirit Mask of Ox": "野牛的野性精神面具",
    "Foul Gnarled Staff of Guarding": "粗结的守卫法杖",
    "Freezing Battle Staff": "冰冻战杖",
    "Garnet Antlers of Regeneration": "石榴石再生的鹿角",
    "Glacial War Staff of Locust": "蝗虫的冰川战争法杖",
    "Glowing Gnarled Staff of Warding": "发光的多节守卫法杖",
    "Greater Healing potion": "强效治疗药水",
    "Greater Mana potion": "强效法力药水",
    "Half freeze duration": "半冻结时间",
    "Horadric Amulet": "赫拉迪克护身符",
    "Increase shrine duration by 20%": "神殿持续时间增加 20%",
    "Iron Jo Staff of Wraith": "幽灵的铁乔权杖",
    "Jagged War Staff of simplicity": "简单的锯齿战争法杖",
    "Jo Staff of Negation": "乔否定法杖",
    "Light healing potion": "光疗药水",
    "Reduce class & skills level requirements by 1": "将职业和技能水平要求降低 1",
    "Ruby Falcon Mask of ease": "红宝石猎鹰面具",
    "Ruby Falcon Mask of Fox": "红宝石猎鹰狐狸面具",
    "Russet Cuirass of Remedy": "赤褐色的补救胸甲",
    "Sapphire Falcon Mask": "蓝宝石猎鹰面具",
    "Savage Long Staff of Carnage": "野蛮杀戮长杖",
    "Scintillating Falcon Mask": "闪烁猎鹰面具",
    "Serpent's Belt of simplicity": "蛇的简单腰带",
    "Shimmering Bone Helm of Accuracy": "精确的闪光骨头盔",
    "Shimmering Falcon Mask of simplicity": "简约的闪亮猎鹰面具",
    "Skullcrusher": "碎颅者",
    "Spirit Mask of ease": "轻松的精神面具",
    "Spirit Mask of Tiger": "虎魂面具",
    "Super Healing potion": "超级治愈药水",
    "Super Mana potion": "超级法力药水",
    "Tangerine Falcon Mask of simplicity": "简单的橘子猎鹰面具",
    "Viridian Antlers of Tiger": "常绿虎角",
    "Viridian Spirit Mask of Memorizing": "常青精神记忆面具",
    "War Staff of ease": "轻松的战争法杖",
    "Beryl Heavy Boots of Gifted": "天才的绿柱石重靴",
    "(unique Leather Boots)": "（独特的皮靴）",
    "(unique Leather Gloves)": "（独特的皮手套）",
    "+2 to apprentice skills level": "+2 学徒技能等级",
    "+2 to Frozen Armor (Sorceress only)": "+2 冰冻护甲（仅限女术士）",
    "50% more experience from monsters": "来自怪物的经验增加 50%",
    "Basinet": "露面钢盔",
    "Cedar Staff": "雪松法杖",
    "Demonhide Sash": "魔皮腰带",
    "Demonhide Sash of Regeneration": "再生魔皮腰带",
    "Firefeet": "火脚",
    "Flanged Mace": "法兰钉头锤",
    "Giant Axe": "巨斧",
    "Gothic Axe of ease": "哥特式轻松之斧",
    "Imbue": "灌输",
    "Lightning Hands": "闪电之手",
    "Lysander": "莱桑德",
    "Shamshir": "虚伪之刃",
    "Sharkskin Boots": "鲨鱼皮靴",
    "Templar Coat": "圣殿骑士外套",
    "Tusk Sword of Slaying": "獠牙杀戮剑",
    "You can try to create a unique item with your shards.": "您可以尝试使用您的碎片创建一个独特的项目。",
    "+2 to barbarian skills level": "+2 野蛮人技能等级",
    "+2 to Combat skills (apprentice only)": "+2 战斗技能（仅限学徒）",
    "+2 to Combat skills (barbarian only)": "+2 战斗技能（仅限野蛮人）",
    "+2 to sorceress skills level": "+2 女术士技能等级",
    "+2 to Summon Wolf (Druid only)": "+2 召唤狼（仅限德鲁伊）",
    "+3 to Cold Mastery (Sorceress only)": "+3 冰冷掌握（仅限女术士）",
    "+3 to Shape Shifting skills (druid only)": "+3 变形技能（仅限德鲁伊）",
    "Alpha Helm": "阿尔法头盔",
    "Alpha Helm of ease": "轻松的阿尔法头盔",
    "Ancient Armor": "古代盔甲",
    "Ancient Armor of Fox": "狐狸古代盔甲",
    "Ancient Axe": "古斧",
    "Ancient Shield": "远古之盾",
    "Ancient Sword": "古剑",
    "Arch-Angel's Sallet": "大天使的小腿",
    "Arcing Twin Axe": "电弧双斧",
    "Barbed Club": "带刺俱乐部",
    "Barbed Shield": "刺盾",
    "Battle Belt": "战斗腰带",
    "Battle Belt of Accuracy": "准确的战斗腰带",
    "Battle Boots": "战靴",
    "Bearded Axe": "胡子斧",
    "Beryl Alpha Helm": "绿柱石阿尔法头盔",
    "Brutal Tusk Sword of Quality": "品质残暴獠牙剑",
    "Casque": "卡斯克",
    "Chaos Armor": "混沌护甲",
    "Cleaver": "切肉刀",
    "Cobalt Mage Plate": "钴法师板甲",
    "Communal Cudgel of Leech": "水蛭的公共棍子",
    "Corrosive Flanged Mace": "腐蚀性法兰钉头锤",
    "Crimson Round Shield": "深红圆盾",
    "Crowbill": "鸦嘴",
    "Cuirass": "胸甲",
    "Cutlass": "弯刀",
    "Dalcian Falx": "达尔西亚镰刀",
    "Dalcian Falx of Slaying": "杀戮之镰",
    "Defender": "后卫",
    "Defender of simplicity": "简单的捍卫者",
    "Demonhide Armor": "魔皮盔甲",
    "Demonhide Gloves": "魔皮手套",
    "Dimensional Blade": "次元之刃",
    "Dragon Shield": "龙盾",
    "Dragon's Sallet": "龙的小卖部",
    "Drake's Chaos Armor": "德雷克的混沌盔甲",
    "Drake's Scutum": "德雷克的盾牌",
    "Embossed Plate": "凸纹战甲",
    "Embossed Plate of Giant": "巨人凸纹战甲",
    "Espandon": "埃斯潘登",
    "Executioner Sword": "刽子手剑",
    "Fanatic Cutlass": "狂热弯刀",
    "Fanatic Espandon": "狂热的西班牙人",
    "Ferocious Ancient Sword of Vampire": "凶猛的吸血鬼古剑",
    "Flanged Mace of ease": "方便的法兰钉头锤",
    "Foul Shamshir": "犯规沙姆希尔",
    "Full Plate": "全身甲",
    "Full Plate of Health": "生命之全身甲",
    "Garnet War Hat": "石榴石战帽",
    "Ghost Armor": "鬼铠",
    "Gladius": "格拉迪乌斯",
    "Glorious Chaos Armor of Life": "光辉混沌生命之铠",
    "Glowing Gladius of ease": "发光的 Gladius 轻松",
    "Gothic Axe": "哥特式斧头",
    "Gothic Axe of Craftsmanship": "哥特式工艺之斧",
    "Gothic Staff": "哥特式法杖",
    "Gothic Sword": "哥特剑",
    "Gothic Sword of Wraith": "幽灵哥特式剑",
    "Grim Helm": "冷酷头盔",
    "Grim Shield": "冷酷之盾",
    "Hatchet": "斧头",
    "Heavy Bracers": "重型护腕",
    "Holy Sharkskin Belt": "圣鲨皮腰带",
    "Hunter's Guise": "猎人的伪装",
    "Increase shrine duration by 29%": "神殿持续时间增加 29%",
    "Jagged Star": "锯齿星",
    "Knout": "打结",
    "Lapis Alpha Helm of Amelioration": "青金石 Alpha 改善头盔",
    "Lapis Casque": "青金石",
    "Linked Mail": "链接邮件",
    "Lizard's Demonhide Gloves": "蜥蜴的魔皮手套",
    "Mage Plate": "法师铠甲",
    "Mesh Belt": "网带",
    "Mesh Boots": "网眼靴子",
    "Military Axe": "军用斧头",
    "Naga": "那加",
    "Naga of Bat": "蝙蝠娜迦",
    "Ocher Trellised Armor of Strength": "赭色格子力量盔甲",
    "Ornate Plate": "华丽战甲",
    "Ornate Plate of Life Everlasting": "永恒生命的华丽盘子",
    "Pavise": "帕维斯",
    "Quarter Staff": "季度工作人员",
    "Raging Jagged Star of Leech": "愤怒的锯齿水蛭之星",
    "Rainbow Basinet": "彩虹露面钢盔",
    "Recruit's War Hat of Precision": "新兵的精确战帽",
    "Ring of Jackal": "豺狼之戒",
    "Rune Staff": "符文法杖",
    "Rune Staff of Wraith": "怨灵符文法杖",
    "Sacred Feathers": "神圣的羽毛",
    "Saintly War Belt": "圣战腰带",
    "Sallet": "轻盔",
    "Scintillating Chaos Armor of Precision": "闪烁的混沌精准护甲",
    "Scutum": "古罗马长盾",
    "Septic Ancient Sword of Bat": "蝙蝠之腐烂古剑",
    "Serpentskin Armor": "蛇皮盔甲",
    "Shamshir of Bat": "蝙蝠之虚伪之刃",
    "Sharkskin Belt": "鲨鱼皮腰带",
    "Sharkskin Boots of ease": "鲨鱼皮靴子",
    "Sharkskin Gloves": "鲨鱼皮手套",
    "Sharktooth Armor": "鲨齿盔甲",
    "Shimmering Battle Belt of Ox": "闪亮的牛战腰带",
    "Shimmering Ornate Plate": "闪闪发光的华丽甲盔甲",
    "Slayer Tabar": "杀手塔巴尔",
    "Smoking Rune Sword of Gore": "戈尔的吸烟符文剑",
    "Snowy Cleaver of Readiness": "雪白的准备砍刀",
    "Static Cleaver": "静态切割器",
    "Steel Battle Sword of ease": "轻松钢战剑",
    "Steel Twin Axe of ease": "轻松的钢双斧",
    "Tigulated Mail": "捆绑邮件",
    "Totemic Mask": "图腾面具",
    "Trellised Armor": "格子盔甲",
    "Tulwar": "弯刀",
    "Tusk Sword": "獠牙剑",
    "Tusk Sword of Leech": "水蛭獠牙剑",
    "Twin Axe": "双斧",
    "Twin Axe of simplicity": "简单的双斧",
    "Twin Axe of Vampire": "吸血鬼双斧",
    "War Belt": "战争腰带",
    "War Belt of Revivification": "复兴之战腰带",
    "War Boots": "战靴",
    "War Gauntlers": "战争手套",
    "War Hat": "战帽",
    "Winged Helm": "翼盔",
    "Zweihander": "德国双手剑",
    "Faithful": "忠诚者",
    "Ismail Vilehand": "邪恶之手伊斯梅尔",
    "Temple Guard": "神殿护卫",
    "Spider Magus": "蜘蛛巫师",
    "Bone Scarab": "骨甲虫",
    "Are you sure you want to exile ?": "你确定要流放吗？",
    "Cancel": "取消",
    "Exile": "流放",
    "Don't forget to store your favorite items in your stash or it will be lost.": "不要忘记将您最喜欢的物品存放在您的藏匿处，否则它会丢失。",
    "You will get": "你将获得",
    "You will keep your stash, shards and unlocked class will remain unlocked.": "您将保留您的藏匿处、碎片和解锁的职业将保持解锁状态。",
    "You will lose everything else: progress, xp, attributes, skills, inventory...": "您将失去其他一切：进度、经验、属性、技能、仓库......",
    "Fiend": "魔王",
    "Poison Spinner": "毒蜘蛛",
    "Flesh Archer": "生灵射手",
    "Sexton": "教堂执事",
    "Night Lord": "夜使者",
    "Zealot": "狂热者",
    "Flesh Hunter": "血肉猎人",
    "Thrasher": "捶打者",
    "Witch Doctor Endugu": "古巫医印都",
    "Toorc Icefirst": "冰拳托克",
    "Flayer": "剥皮者",
    "Infidel": "异教徒",
    "Blood Diver": "嗜血蝙蝠",
    "Bramble Hulk": "荆棘绿巨人",
    "Flamespike": "烈焰尖刺",
    "Sszark The Burning": "燃烧者韦布",
    "Wailing Beast": "哀泣兽",
    "Hell Buzzard": "地狱秃鹰",
    "Cantor": "领唱者",
    "Cloud Stalker": "潜云兽",
    "Heirophant": "大祭师",
    "Geleb Flamefinger": "火焰之指吉列布",
    "- Magic resistant": "- 魔法抗性",
    "Area attack - Summon Faithful": "区域攻击 - 召唤忠实",
    "Area attack - Summon Flayer": "区域攻击 - 召唤剥皮者",
    "Area attack - Summon Infidel": "区域攻击 - 召唤异教徒",
    "Area attack - Summon Zealot": "区域攻击 - 召唤狂热者",
    "Extra strong -": "超强——",
    "Extra strong - Extra fast": "超强 - 超快",
    "Extra strong - Magic resistant - Area attack - Summon Flayer": "超强 - 魔法抗性 - 范围攻击 - 召唤剥皮者",
    "Flayer Shaman": "剥皮者萨满",
    "Gloam": "黄昏",
    "Light Gauntlets of Renewal": "复兴的轻型护手",
    "Soul Killer": "灵魂杀手",
    "Stun Attack": "眩晕攻击",
    "(unique Cudgel)": "（独特的棍棒）",
    "(unique Falcon Mask)": "（独特的猎鹰面具）",
    "(unique Giant Axe)": "（独特的巨斧）",
    "(unique Gothic Sword)": "（独特的哥特剑）",
    "(unique Great Helm)": "（独特的大头盔）",
    "(unique Ornate Plate)": "（独特的华丽盘子）",
    "+1 to druid skills level": "+1 德鲁伊技能等级",
    "+1 to Shape Shifting skills (druid only)": "+1 变形技能（仅限德鲁伊）",
    "+1 to sorceress skills level": "+1 女术士技能等级",
    "+1 to Summoning skills (druid only)": "+1 召唤技能（仅限德鲁伊）",
    "+10 energy (permanently)": "+10 能量（永久）",
    "+2 to all skills": "+2 所有技能",
    "+2 to druid skills level": "+2 德鲁伊技能等级",
    "+2 to Fire Mastery (Sorceress only)": "+2 火焰掌握（仅限女术士）",
    "+2 to Heat (Sorceress only)": "+2 加热（仅限女术士）",
    "+2 to Summon Resist (Druid only)": "+2 召唤抗性（仅限德鲁伊）",
    "+2 to Summoning skills (druid only)": "+2 召唤技能（仅限德鲁伊）",
    "+2 to Werewolf (Druid only)": "+2 狼人（仅限德鲁伊）",
    "+3 to Fire Mastery (Sorceress only)": "+3 火焰掌握（仅限女术士）",
    "+3 to Frozen Armor (Sorceress only)": "+3 冰冻护甲（仅限女术士）",
    "+3 to Frozen Orb (Sorceress only)": "+3 冰冻宝珠（仅限女术士）",
    "+3 to Heat (Sorceress only)": "+3 加热（仅限女术士）",
    "+3 to Summon Mastery (Druid only)": "+3 召唤精通（仅限德鲁伊）",
    "+3 to Summon Pixie (Druid only)": "+3 召唤小精灵（仅限德鲁伊）",
    "+3 to Summon Resist (Druid only)": "+3 召唤抗性（仅限德鲁伊）",
    "+3 to Summoning skills (druid only)": "+3 召唤技能（仅限德鲁伊）",
    "+3 to Werebear (Druid only)": "+3 熊人（仅限德鲁伊）",
    "100% better chance of getting magic items": "获得魔法物品的几率提高 100%",
    "200% more gold from monsters": "来自怪物的金币增加 200%",
    "25% better chance of getting shards": "获得碎片的几率提高 25%",
    "40% better chance of getting magic items": "获得魔法物品的几率提高 40%",
    "Amber Antlers of Fox": "狐狸的琥珀鹿角",
    "Amber Antlers of simplicity": "简单的琥珀鹿角",
    "Amber Antlers of Skill": "技能的琥珀鹿角",
    "Amber Spirit Mask of Continuance": "琥珀精神永续面具",
    "Angel's Battle Staff of Alacrity": "天使的战斗之杖",
    "Angel's Battle Staff of Warding": "天使的守护之战法杖",
    "Angel's Gnarled Staff of Carnage": "天使的多节杀戮法杖",
    "Angel's Gnarled Staff of Warding": "天使的多节守卫法杖",
    "Angel's War Staff of Wraith": "天使之战 怨灵之杖",
    "Arch-Angel's Battle Staff of Carnage": "大天使的杀戮之战法杖",
    "Arch-Angel's Jo Staff of Worth": "大天使的价值之杖",
    "Avenger Guard": "复仇者守卫",
    "Azure Antlers of Colossus": "巨像的蔚蓝鹿角",
    "Azure Falcon Mask of simplicity": "简单的天蓝色猎鹰面具",
    "Azure Hawk Helm of ease": "轻松的青鹰头盔",
    "Azure Spirit Mask of Memorizing": "青色记忆之灵面具",
    "Azure Spirit Mask of Precision": "精准的碧蓝精灵面具",
    "Azure Spirit Mask of simplicity": "朴素的碧蓝精灵面具",
    "Babr-e Bayan": "巴布雷巴扬",
    "Beryl Antlers of Renewal": "再生绿柱石鹿角",
    "Beryl Antlers of Skill": "技能的绿柱石鹿角",
    "Beryl Falcon Mask of Amelioration": "绿柱石猎鹰改善面具",
    "Beryl Falcon Mask of ease": "Beryl Falcon 轻松面具",
    "Beryl Falcon Mask of simplicity": "简单的绿柱石猎鹰面具",
    "Beryl Hawk Helm of Amelioration": "绿柱石鹰改善头盔",
    "Beryl Hawk Helm of Regrowth": "绿柱石鹰再生头盔",
    "Beryl Hawk Helm of Resumption": "恢复的绿柱石鹰头盔",
    "Beryl Hawk Helm of Skill": "绿柱石鹰技能头盔",
    "Beryl Wolf Head of Steadiness": "Beryl Wolf 稳定负责人",
    "Blazing Battle Staff of ease": "轻松的炽热战斗法杖",
    "Blazing Battle Staff of Magus": "魔法师的炽热战斗法杖",
    "Blazing Gnarled Staff of Bat": "炽热多节的蝙蝠法杖",
    "Blazing Gnarled Staff of Craftsmanship": "燃烧的多节工艺法杖",
    "Blazing Gnarled Staff of Excellence": "炽热多节的卓越法杖",
    "Blazing Long Staff of simplicity": "简单的炽热长杖",
    "Blazing War Staff of Leech": "炽热的水蛭战杖",
    "Blazing War Staff of Locust": "炽热的蝗虫战杖",
    "Blood Lord": "血之领主",
    "Boreal Battle Staff of Gore": "戈尔的北方战斗法杖",
    "Boreal Gnarled Staff of ease": "寒风刺骨的安逸法杖",
    "Boreal War Staff of Readiness": "北方战备法杖",
    "Bronze Battle Staff of Quality": "质量青铜战斗法杖",
    "Bronze Gnarled Staff of Bat": "青铜多节蝙蝠法杖",
    "Bronze Long Staff of Magus": "魔法师的青铜长杖",
    "Bronze Short Staff of Quality": "青铜质量短杖",
    "Bronze War Staff of Excellence": "卓越的青铜战争法杖",
    "Bronze War Staff of Readiness": "青铜战备法杖",
    "Bronze War Staff of Slaying": "杀戮之青铜战杖",
    "Bronze War Staff of Warding": "青铜战争守卫法杖",
    "Brutal Battle Staff of Quality": "质量野蛮战斗法杖",
    "Brutal Gnarled Staff of Alacrity": "野蛮粗糙的敏捷法杖",
    "Brutal Gnarled Staff of Negation": "野蛮多节的否定法杖",
    "Brutal Gnarled Staff of Readiness": "野蛮多节准备法杖",
    "Brutal Long Staff of Guarding": "残酷的守护长杖",
    "Brutal War Staff of Magus": "巫师的残酷战争法杖",
    "Brutal War Staff of Swiftness": "野蛮战争迅捷法杖",
    "Burning Gnarled Staff of Carnage": "燃烧的杀戮之杖",
    "Burning War Staff of Magus": "魔法师的燃烧战杖",
    "Buzzing Battle Staff of Craftsmanship": "嗡嗡作响的工匠之战法杖",
    "Buzzing Long Staff of Carnage": "嗡嗡作响的屠杀长杖",
    "Buzzing Long Staff of ease": "嗡嗡作响的轻松长法杖",
    "Buzzing War Staff of Guarding": "嗡嗡的守卫战杖",
    "Buzzing War Staff of Locust": "嗡嗡的蝗虫战杖",
    "Buzzing War Staff of Quality": "嗡嗡作响的质量参战人员",
    "Buzzing War Staff of Warding": "嗡嗡的战争法杖",
    "Caretaker's Antlers of Accuracy": "看守者的精准鹿角",
    "Caretaker's Antlers of Resumption": "恢复看守的鹿角",
    "Caretaker's Antlers of Thawing": "看守人的解冻鹿角",
    "Caretaker's Falcon Mask of Strength": "看守者的猎鹰力量面具",
    "Caretaker's Spirit Mask of Fox": "看守者的灵魂狐狸面具",
    "Caretaker's Spirit Mask of Giant": "看守者的巨人精神面具",
    "Chilling Battle Staff of Apprentice": "寒冰学徒之战法杖",
    "Chilling Battle Staff of Warding": "寒冷的守卫之战法杖",
    "Chilling Long Staff of Bat": "令人不寒而栗的蝙蝠长杖",
    "Chilling Long Staff of Guarding": "冰冷的守护之杖",
    "Chilling Long Staff of Sentinel": "寒冷的哨兵长杖",
    "Chilling War Staff of Slaying": "令人毛骨悚然的杀戮之杖",
    "Cobalt Antlers of Resumption": "恢复的钴鹿角",
    "Cobalt Falcon Mask of Continuance": "钴隼永续面具",
    "Cobalt Hawk Helm of Strength": "钴鹰力量头盔",
    "Communal Falcon Mask of Fox": "狐狸的公共猎鹰面具",
    "Coral Antlers of simplicity": "简单的珊瑚鹿角",
    "Coral Falcon Mask of Skill": "技能珊瑚猎鹰面具",
    "Coral Spirit Mask of Regeneration": "珊瑚精灵再生面具",
    "Coral Wolf Head of ease": "珊瑚狼头轻松",
    "Corrosive Battle Staff of Gore": "腐蚀性的戈尔战斗法杖",
    "Corrosive Battle Staff of Guarding": "腐蚀战斗法杖",
    "Corrosive Battle Staff of Measure": "腐蚀战斗法杖",
    "Corrosive Battle Staff of Quality": "腐蚀战斗法杖",
    "Corrosive Battle Staff of Worth": "腐蚀战斗法杖",
    "Corrosive Gnarled Staff of Warding": "腐蚀性多节守卫法杖",
    "Corrosive Long Staff of Alacrity": "腐蚀的敏捷长杖",
    "Corrosive Long Staff of Bat": "腐蚀蝙蝠长杖",
    "Corrosive Long Staff of Leech": "腐蚀水蛭长杖",
    "Corrosive Long Staff of Measure": "腐蚀性长杖",
    "Corrosive Long Staff of Sentinel": "腐蚀的哨兵长杖",
    "Crimson Antlers of Accuracy": "精准的深红鹿角",
    "Crimson Falcon Mask of Fox": "深红猎鹰狐狸面具",
    "Crimson Hawk Helm of Renewal": "重生之鹰头盔",
    "Crimson Hawk Helm of simplicity": "简单的深红鹰头盔",
    "Crimson Wolf Head of Amelioration": "赤狼改善团长",
    "Crimson Wolf Head of Continuance": "Crimson Wolf 持续负责人",
    "Deadly Battle Staff of Bat": "蝙蝠致命战杖",
    "Deadly Battle Staff of Magus": "魔法使的致命战斗法杖",
    "Deadly Battle Staff of Worth": "致命的战斗法杖",
    "Deadly Gnarled Staff of Craftsmanship": "致命的多节工艺法杖",
    "Deadly Gnarled Staff of Gore": "致命的多节戈尔法杖",
    "Deadly Long Staff of Craftsmanship": "致命的长手工艺",
    "Death Guard": "死亡守卫",
    "Dragon's Antlers of Tiger": "龙之虎角",
    "Dragon's Falcon Mask of Amelioration": "龙之隼改善面具",
    "Dragon's Hawk Helm of Memorizing": "龙鹰记忆头盔",
    "Dragon's Hawk Helm of Steadiness": "龙鹰稳定头盔",
    "Dragon's Spirit Mask of Renewal": "龙魂更新面具",
    "Dragon's Spirit Mask of Strength": "龙魂力量面具",
    "Drake's Antlers of ease": "德雷克的安逸鹿角",
    "Drake's Antlers of Resumption": "德雷克的恢复鹿角",
    "Durance of Hate": "憎恨的囚牢",
    "Eagle Mask": "鹰面具",
    "Emerald Antlers of Amelioration": "改良的翡翠鹿角",
    "Emerald Falcon Mask of Accuracy": "翡翠猎鹰精准面具",
    "Emerald Falcon Mask of Continuance": "持续的翡翠猎鹰面具",
    "Emerald Falcon Mask of Jackal": "翡翠猎鹰豺狼面具",
    "Emerald Hawk Helm of simplicity": "简单的翡翠鹰头盔",
    "Emerald Spirit Mask of Accuracy": "翡翠精神精准面具",
    "Emerald Spirit Mask of Amelioration": "翡翠灵改善面具",
    "Emerald Wolf Head of Colossus": "翡翠狼巨像头",
    "Feral Antlers of Continuance": "延续的野性鹿角",
    "Feral Falcon Mask of Steadiness": "野性猎鹰镇定面具",
    "Feral Falcon Mask of Tiger": "野隼虎面具",
    "Feral Hawk Helm of Accuracy": "野鹰精准头盔",
    "Feral Wolf Head of Wolf": "野狼狼头",
    "Ferocious Jo Staff of Bat": "凶猛的乔蝙蝠之杖",
    "Fiery Battle Staff of Guarding": "炽热的守护之战法杖",
    "Fiery Battle Staff of simplicity": "简单的火热战斗法杖",
    "Fiery Gnarled Staff of ease": "炽热多节法杖",
    "Fiery Gnarled Staff of Leech": "炽热多节的水蛭法杖",
    "Fiery Gnarled Staff of Swiftness": "火热多节的迅捷法杖",
    "Fiery Long Staff of Magus": "魔法师的炽热长法杖",
    "Fiery War Staff of ease": "炽热战争法杖",
    "Fiery War Staff of Slaying": "炽热的杀戮之杖",
    "Foul Battle Staff of Bat": "蝙蝠恶战法杖",
    "Foul Gnarled Staff of Leech": "肮脏的水蛭法杖",
    "Foul Gnarled Staff of Slaying": "邪恶的杀戮之杖",
    "Foul War Staff of Warding": "守卫的恶战法杖",
    "Foul War Staff of Worth": "恶战法杖",
    "Freezing Battle Staff of Bat": "冰冻蝙蝠战杖",
    "Freezing Battle Staff of Guarding": "冰冻守护之战法杖",
    "Freezing Battle Staff of Leech": "冰冻水蛭战杖",
    "Freezing Battle Staff of Sentinel": "冰冻哨兵战杖",
    "Freezing Battle Staff of simplicity": "简单的冰冻战斗法杖",
    "Freezing Gnarled Staff of Bat": "冰冻多节蝙蝠法杖",
    "Freezing War Staff of Leech": "冰冻水蛭战杖",
    "Garnet Hawk Helm of Remedy": "石榴石鹰治疗头盔",
    "Garnet Hawk Helm of simplicity": "简单的石榴石鹰头盔",
    "Garnet Hawk Helm of Tiger": "石榴石鹰之虎头盔",
    "Garnet Spirit Mask of Might": "石榴石精神力量面具",
    "Garnet Spirit Mask of Remedy": "石榴石灵药面罩",
    "Gloden Coat": "金色大衣",
    "Glorious Antlers of Amelioration": "光荣的改良鹿角",
    "Glorious Antlers of Continuance": "光荣的鹿角延续",
    "Glorious Falcon Mask of Amelioration": "光荣的猎鹰改善面具",
    "Glorious Falcon Mask of simplicity": "光荣的猎鹰面具 简约",
    "Glorious Hawk Helm of Might": "光辉之鹰力量头盔",
    "Glorious Hawk Helm of simplicity": "极简之光辉之鹰头盔",
    "Glowing Battle Staff of Bat": "发光的蝙蝠战杖",
    "Glowing Battle Staff of Swiftness": "发光的迅捷战斗法杖",
    "Glowing Short Staff of Slaying": "发光的杀戮短杖",
    "Gold Battle Staff of Excellence": "卓越的黄金战斗法杖",
    "Gold Battle Staff of Gore": "戈尔黄金战杖",
    "Gold Battle Staff of Swiftness": "迅捷金战斗法杖",
    "Gold Jo Staff of Carnage": "杀戮之金乔法杖",
    "Gold Long Staff of ease": "轻松的金长杖",
    "Guardian of Earth": "地球守护者",
    "Ice ring": "冰环",
    "Ice Wraith": "冰之幽灵",
    "Iron Battle Staff of Apprentice": "学徒铁战法杖",
    "Iron Long Staff of simplicity": "简单的铁长杖",
    "Iron War Staff of ease": "轻松的钢铁战法杖",
    "Jade Antlers of simplicity": "简约的玉鹿角",
    "Jade Antlers of Tiger": "玉虎角",
    "Jade Falcon Mask of Might": "玉隼威能面具",
    "Jade Hawk Helm of Colossus": "巨像的翡翠鹰头盔",
    "Jade Hawk Helm of Fox": "狐狸的翡翠鹰头盔",
    "Jade Hawk Helm of Regrowth": "再生翡翠鹰头盔",
    "Jade Spirit Mask of ease": "玉灵轻松面具",
    "Jade Spirit Mask of Regrowth": "再生玉灵面具",
    "Jagged Gnarled Staff of Worth": "锯齿多节法杖",
    "Jagged Long Staff of Bat": "锯齿状长棒蝙蝠",
    "Jagged Long Staff of Slaying": "锯齿长长的杀戮法杖",
    "Jagged War Staff of Swiftness": "锯齿状的迅捷战杖",
    "Jökulsnautr": "杰古斯瑙特",
    "Lapis Antlers of ease": "轻松的青金石鹿角",
    "Lapis Falcon Mask of Wolf": "狼的青金石猎鹰面具",
    "Lapis Wolf Head of Dexterity": "青金狼 灵巧之首",
    "Lizard's Antlers of Jackal": "蜥蜴的豺狼角",
    "Lizard's Hawk Helm of Renewal": "蜥蜴之鹰再生头盔",
    "Mauler": "毛勒",
    "Mind's Eye": "心灵的眼睛",
    "Nagelring": "内格尔林",
    "Ocher Antlers of Fox": "狐狸的赭色鹿角",
    "Ocher Spirit Mask of Wolf": "赭色狼灵面具",
    "Old Boots": "旧靴子",
    "Parashu": "帕拉舒",
    "Prismatic Falcon Mask of Remedy": "棱镜猎鹰补救面具",
    "Rainbow Antlers of ease": "轻松的彩虹鹿角",
    "Rainbow Antlers of Renewal": "复兴的彩虹鹿角",
    "Rainbow Falcon Mask of Fox": "彩虹猎鹰狐狸面具",
    "Rainbow Falcon Mask of Wolf": "狼的彩虹猎鹰面具",
    "Rainbow Spirit Mask of Continuance": "虹灵不灭面具",
    "Rainbow Spirit Mask of simplicity": "简约的彩虹精灵面具",
    "Reduce class & skills level requirements by 3": "将课程和技能等级要求降低 3",
    "Ruby Hawk Helm of Strength": "红宝石鹰力量头盔",
    "Ruby Hawk Helm of Thawing": "红宝石鹰解冻头盔",
    "Ruby Spirit Mask of Memorizing": "红宝石精神记忆面具",
    "Ruby Spirit Mask of Remedy": "红宝石精神面具",
    "Russet Falcon Mask of ease": "赤褐色猎鹰轻松面具",
    "Russet Falcon Mask of Resumption": "恢复的黄褐色猎鹰面具",
    "Russet Hawk Helm of Accuracy": "赤褐色鹰精确头盔",
    "Russet Hawk Helm of Renewal": "黄褐色鹰更新头盔",
    "Saintly Hawk Helm of Dexterity": "圣鹰灵巧头盔",
    "Sapphire Antlers of Memorizing": "记忆的蓝宝石鹿角",
    "Sapphire Falcon Mask of Regeneration": "蓝宝石猎鹰再生面具",
    "Sapphire Hawk Helm of simplicity": "简约的蓝宝石鹰头盔",
    "Savage Battle Staff of Bat": "野蛮战斗法杖",
    "Savage Battle Staff of Leech": "野蛮战斗水蛭法杖",
    "Savage Gnarled Staff of Carnage": "野蛮多节的屠杀法杖",
    "Savage Gnarled Staff of Locust": "野蛮多节的蝗虫法杖",
    "Savage War Staff of Guarding": "野蛮战争守卫法杖",
    "Scintillating Ring of Wraith": "闪烁的幽灵戒指",
    "Scintillating Wolf Head of ease": "闪耀狼头轻松",
    "Septic Battle Staff of Apprentice": "学徒化粪池战斗法杖",
    "Septic Battle Staff of Bat": "蝙蝠的化粪池战斗法杖",
    "Septic Battle Staff of Craftsmanship": "化粪池战斗手艺法杖",
    "Septic Battle Staff of Readiness": "化粪池战备法杖",
    "Septic Battle Staff of simplicity": "简单的化粪池战斗法杖",
    "Septic Gnarled Staff of Leech": "腐烂的水蛭法杖",
    "Septic Gnarled Staff of simplicity": "化粪池粗糙的简单法杖",
    "Septic Long Staff of Guarding": "化粪池长杖",
    "Septic Long Staff of Leech": "水蛭的化脓长杖",
    "Septic Long Staff of Slaying": "杀戮长杖",
    "Septic War Staff of Quality": "化脓性战争质量参谋部",
    "Serpent's Antlers of Amelioration": "蛇的改善鹿角",
    "Serpent's Falcon Mask of Thawing": "毒蛇猎鹰解冻面具",
    "Serpent's Hawk Helm of Regrowth": "蛇之鹰再生头盔",
    "Shaman's Falcon Mask of Resumption": "萨满的猎鹰恢复面具",
    "Shaman's Hawk Helm of Amelioration": "萨满之鹰改善头盔",
    "Shaman's Wolf Head of Resumption": "萨满之狼头颅恢复",
    "Shimmering Antlers of Steadiness": "闪亮的稳定鹿角",
    "Shivering Battle Staff of Bat": "颤抖的蝙蝠战杖",
    "Shivering Battle Staff of Excellence": "颤抖的卓越战斗法杖",
    "Shivering Battle Staff of Readiness": "颤抖的战备法杖",
    "Shivering Gnarled Staff of Alacrity": "颤抖的粗糙之杖",
    "Shivering Gnarled Staff of Slaying": "颤抖的杀戮之杖",
    "Shivering Long Staff of Bat": "颤抖的蝙蝠长杖",
    "Shivering Long Staff of Readiness": "颤抖的长长的准备法杖",
    "Shivering Long Staff of simplicity": "颤抖的长杖",
    "Shivering War Staff of Bat": "颤抖的蝙蝠战杖",
    "Shivering War Staff of Excellence": "颤抖的卓越战争法杖",
    "Shivering War Staff of Negation": "颤抖的否定战杖",
    "Shivering War Staff of Warding": "颤抖的战争法杖",
    "Silver Battle Staff of Apprentice": "学徒白银战杖",
    "Silver Battle Staff of ease": "轻松的银色战斗法杖",
    "Silver Battle Staff of Sentinel": "哨兵银色战斗法杖",
    "Silver War Staff of Warding": "银战守卫法杖",
    "Smoking Battle Staff of Carnage": "大屠杀的吸烟战杖",
    "Smoking Battle Staff of Warding": "吸烟的守卫战斗人员",
    "Smoking Gnarled Staff of Wraith": "吸烟的怨灵之杖",
    "Smoking Long Staff of Apprentice": "学徒吸烟长杖",
    "Smoldering War Staff of Craftsmanship": "闷烧的工匠之杖",
    "Smoldering War Staff of simplicity": "简单的阴燃战争法杖",
    "Smoldering War Staff of Warding": "阴燃战争守卫法杖",
    "Snake's Falcon Mask of Fox": "蛇的猎鹰狐狸面具",
    "Snake's Spirit Mask of Remedy": "蛇灵灵药面具",
    "Snowy Gnarled Staff of Quality": "白雪皑皑的质量法杖",
    "Snowy Long Staff of Wraith": "白雪皑皑的怨灵长杖",
    "Snowy War Staff of Alacrity": "雪域战法杖",
    "Snowy War Staff of ease": "雪域战争法杖",
    "Snowy War Staff of Slaying": "雪域杀戮之杖",
    "Snowy War Staff of Worth": "白雪皑皑的战争法杖",
    "Spiritual Hawk Helm of Jackal": "豺狼灵鹰头盔",
    "Static Battle Staff of Leech": "水蛭的静态战斗法杖",
    "Static Battle Staff of Locust": "蝗虫静态战斗法杖",
    "Static Battle Staff of Quality": "质量静态战斗法杖",
    "Static Battle Staff of simplicity": "简单的静态战斗法杖",
    "Static Gnarled Staff of Alacrity": "静电多节的敏捷法杖",
    "Static Gnarled Staff of Bat": "静电多节蝙蝠法杖",
    "Static Gnarled Staff of ease": "静态多节法杖",
    "Static Long Staff of Locust": "蝗虫静电长杖",
    "Static War Staff of ease": "轻松的静态战争法杖",
    "Static War Staff of Leech": "水蛭静态战杖",
    "Static War Staff of Slaying": "杀戮的静态战争法杖",
    "Static War Staff of Worth": "静态战争法杖",
    "Steel Battle Staff of Leech": "水蛭钢铁战杖",
    "Steel Gnarled Staff of Bat": "钢节蝙蝠法杖",
    "Steel Gnarled Staff of Locust": "钢节蝗虫法杖",
    "Steel Long Staff of Craftsmanship": "精钢长杖",
    "Steel Long Staff of Guarding": "钢制长杖守护",
    "Steel Long Staff of Quality": "钢龙品质员工",
    "Strong Hawk Helm of Steadiness": "坚固的鹰头盔",
    "Strong Spirit Mask of Accuracy": "精准的强灵面具",
    "Strong Spirit Mask of Continuance": "强大的永续精神面具",
    "Student's robe": "学生长袍",
    "Sturdy Antlers of Thawing": "解冻的坚固鹿角",
    "Sturdy Wolf Head of simplicity": "粗壮的狼头简约",
    "Tangerine Spirit Mask of Continuance": "橘魂不灭面具",
    "Trainer's Falcon Mask of Remedy": "训练师的猎鹰治疗面具",
    "Trainer's Falcon Mask of simplicity": "训练师的猎鹰面具简约",
    "Trainer's Wolf Head of Might": "驯兽师的狼头",
    "Traveler's protector": "旅行者的保护者",
    "Viridian Falcon Mask of Wolf": "常绿猎鹰狼面具",
    "Volcanic War Staff of Excellence": "火山战争卓越法杖",
    "(lightning)": "（闪电）",
    "(poison)": "（毒）",
    "+3 to Lycanthropy (Druid only)": "+3 变狼术（仅限德鲁伊）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Elly": "艾莉",
    "Resistant": "抗性",
    "Isolde": "伊索尔德",
    "Amplisa": "安普丽莎",
    "Alhizeer": "阿尔希泽尔",
    "Ahsab": "阿萨布",
    "Rakanishu": "拉卡尼休",
    "Sharyn": "莎琳",
    "Rozene": "罗赞",
    "Fiona": "菲奥娜",
    "Fazel": "法泽尔",
    "v. beta.0.3.3 - Power of Nature": "v. beta.0.3.3 - 自然的力量",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Save ": "保存 ",
    "level ": "等级 ",
    "xp: ": "经验: ",
    "Blood Moor ": "血之沼泽 ",
    "Available points: ": "可用点数：",
    "Damage: ": "伤害: ",
    "Defense: ": "防御: ",
    "Price: ": "价格: ",
    "Speed: ": "速度: ",
    "Potion dropped: ": "药水掉落: ",
    "Restore mana: ": "恢复法力: ",
    "Restore life: ": "恢复生命值: ",
    "Required level: ": "要求等级: ",
    "Damage inflicted: ": "造成的伤害: ",
    "Stun duration: ": "眩晕时长: ",
    "Life: ": "生命值: ",
    "Mana Cost: ": "法力成本: ",
    "Heal: ": "治疗: ",
    "Duration: ": "持续时间: ",
    "Bonus: ": "奖励: ",
    "Chances to block: ": "格挡几率: ",
    "Gold dropped: ": "黄金掉落: ",
    "Extra Slots: ": "额外插槽: ",
    "Type: ": "类型: ",
    "Attack rating: ": "攻击率：",
    "Level required: ": "要求等级：",
    "Required strength: ": "力量要求：",
    "Unlocked: ": "解锁：",
    "Shrine of Resist Fire ": "火抗神殿",
    "Den of Evil ": "邪恶巢穴 ",
    "New area available: ": "新区域可用：",
    "Attack Rating ": "攻击率 ",
    "Life +": "生命值 +",
    "Mana +": "法力 +",
    "Dexterity +": "灵巧 +",
    "Defense +": "防御 +",
    "Damage +": "伤害 +",
    "Strength +": "力量 +",
    "Cold Resist +": "抗寒 +",
    "Cold Plains ": "寒冷平原 ",
    "Poison length ": "毒药长度 ",
    "Reset attr & skills ": "重置属性和技能 ",
    "Hirelings: ": "招聘: ",
    "Fire Resist +": "火抗 +",
    "Forgotten Tower ": "遗忘之塔 ",
    "Black Marsh ": "黑沼泽 ",
    "Minor healing potion ": "小生命药水 ",
    "Minor mana potion ": "小法力药水 ",
    "Thawing Potion ": "解冻药水 ",
    "Antidote ": "解药 ",
    "Attack Rate +": "攻击率 +",
    "Gives potion every ": "给予药水每隔 ",
    "Storage: ": "仓库: ",
    "Level: ": "等级: ",
    "Lightning Resist +": "闪电抗性 +",
    "Chances to block +": "格挡几率 +",
    "Resplenish mana +": "回复法力 +",
    "Required dexterity: ": "要求的灵巧：",
    "Burial Grounds ": "墓地",
    "Cave ": "洞穴",
    "Crypt ": "地下室",
    "Dark Wood ": "黑暗森林 ",
    "Mausoleum ": "陵墓",
    "Stony Field ": "石场",
    "Tristram ": "崔斯特瑞姆",
    "Underground Passage ": "地下通道",
    "Poison Resist +": "毒抗 +",
    "Summon crow level: ": "召唤乌鸦等级：",
    "Magic missile cast: ": "魔法飞弹施放：",
    "Kill Rakanishu: ": "杀死拉卡尼休：",
    "Max mana: ": "最大法力：",
    "Relics: ": "遗物：",
    "Class: ": "职业：",
    "Exile ": "流放（转生）",
    "Shrine of Armor ": "盔甲神殿 ",
    "Vikhyat ": "维克亚特 ",
    "The Hole ": "洞窟 ",
    "Tamoe Highland ": "泰摩高地 ",
    "Resplenish life +": "生命值上限 +",
    "Resist all +": "全部抗性 +",
    "The Pit ": "深渊 ",
    "Vikhyat ": "维克亚特 ",
    "Monastery Gate ": "修道院大门 ",
    "Shards to use: ": "使用的碎片：",
    "Life gainded after kill: ": "击杀后获得的生命值：",
    "Chances of success: ": "成功率：",
    "Attack speed: ": "攻击速度：",
    "Spell cost: ": "法术成本：",
    "Total Bonus: ": "总奖励：",
    "Kurast Docks ": "库拉斯特海港 ",
    "Absorbs: ": "吸收：",
    "Travincal ": "崔凡克城 ",
    "Light healing potion ": "轻型治疗药水 ",
    "Light mana potion ": "轻型法力药水 ",
    "Mana potion ": "法力药水 ",
    "Healing potion ": "治疗药水 ",
    "Greater Healing potion ": "强效治疗药水 ",
    "Greater Mana potion ": "强效法力药水 ",
    "Super Healing potion ": "超级治疗药水 ",
    "Super Mana potion ": "超级法力药水 ",
    "Lut Gholein ": "鲁高因 ",
    "Requirements ": "要求 ",
    "Damage Reduced by ": "伤害降低 ",
    "Xp gain per relic: ": "每个遗物的 经验 增益：",
    "Xp gain: ": "经验增益: ",
    "Energy Potion": "能量药水",
    "Cast rate +": "释放率 +",
    "Increase shrine duration by ": "神殿持续时间增加 ",
    "Magical damage Reduced by ": "魔法伤害减少",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "You have been killed by Gargantuan Beast. Xp lost: ": "你被 巨兽 杀死了。 经验丢失：",
    "You have been killed by Zombie. Xp lost: ": "你被 僵尸 杀死了。 经验丢失：",
    "You have been killed by Quill Rat. Xp lost: ": "你被 毛老鼠 杀死了。 经验丢失：",
    "Zombie died. Xp earned: ": "僵尸死了。 获得经验：",
    "Quill Rat died. Xp earned: ": "毛老鼠死了。获得经验：",
    "Fallen died. Xp earned: ": "堕落者死了。 获得经验: ",
    "Gargantuan Beast died. Xp earned: ": "巨兽死了。 获得经验: ",
    "Fallen Shaman died. Xp earned: ": "堕落萨满死了。 获得经验：",
    "": "",
    "Gargantuan Beast: Hit ": "巨兽: 命中",
    "Hungry Dead: Hit ": "饿死鬼: 命中",
    "The Countess: Hit ": "伯爵夫人: 命中",
    "Rakanishu: Hit ": "洛卡尼修: 命中",
    "Carver Shaman: Hit ": "利刃魔萨满: 命中",
    "Skeleton: Hit ": "骷髅: 命中",
    "Devilkin: Hit ": "恶魔人: 命中",
    "Blood Clan: Hit ": "血族: 命中",
    "Night Clan: Hit ": "夜族: 命中",
    "Returned Mage: Hit ": "回归法师: 命中",
    "Ghost: Hit ": "鬼魂: 命中",
    "Carver: Hit ": "利刃魔: 命中",
    "Griswold: Hit ": "格里斯沃尔德: 命中",
    "Vile Hunter: Hit ": "邪恶猎人: 命中",
    "Misshapen: Hit ": "异形: 命中",
    "Skeleton Archer: Hit ": "骷髅弓箭手: 命中",
    "Spike Fiend: Hit ": "刺魔: 命中",
    "Treehead Woodfist: Hit ": "树头木拳: 命中",
    "Returned: Hit ": "回归者: 命中",
    "Dark Stalker: Hit ": "黑暗猎手: 命中",
    "Vikhyat: Hit ": "维克亚特: 命中",
    "Vile Archer: Hit ": "邪恶弓箭手: 命中",
    "Dark Ranger: Hit Vikhyat ": "黑暗游侠: 命中 维克亚特",
    "Dark Ranger: Hit ": "黑暗游侠: 命中",
    "Disfigured: Hit ": "毁容者: 命中",
    "Returned Archer: Hit ": "回归弓箭手: 命中",
    "Hell Cat: Hit ": "地狱猫: 命中",
    "Yeti: Hit ": "雪人: 命中",
    "Steel Scarab: Hit ": "钢铁圣甲虫: 命中",
    "Apparition: Hit ": "幽灵: 命中",
    "Flesh Hunter: Hit ": "荆棘绿巨人: 命中",
    "Flayer: Hit ": "剥皮者: 命中",
    "Zealot: Hit ": "狂热者: 命中",
    "Faithful: Hit ": "忠诚者: 命中",
    "Ismail Vilehand: Hit ": "邪恶之手伊斯梅尔: 命中",
    "Temple Guard: Hit ": "神殿护卫: 命中",
    "Bone Scarab: Hit ": "骨甲虫: 命中",
    "Poison Spinner: Hit ": "毒蜘蛛: 命中",
    "Night Lord: Hit ": "夜使者: 命中",
    "Fiend: Hit ": "魔王: 命中",
    "Blood Diver: Hit ": "嗜血蝙蝠: 命中",
    "Toorc Icefirst: Hit ": "冰拳托克: 命中",
    "Thrasher: Hit ": "捶打者: 命中",
    "Witch Doctor Endugu: Hit ": "古巫医印都: 命中",
    "Sexton: Hit ": "教堂执事: 命中",
    "Flesh Archer: Hit ": "生灵射手: 命中",
    "Bramble Hulk: Hit ": "僵尸: 命中",
    "Flamespike: Hit ": "烈焰尖刺: 命中",
    "Geleb Flamefinger: Hit ": "火焰之指吉列布: 命中",
    "Heirophant: Hit ": "大祭师: 命中",
    "Zombie: Hit ": "僵尸: 命中",
    "Cantor: Hit ": "领唱者: 命中",
    "Cloud Stalker: Hit ": "潜云兽: 命中",
    "Hell Buzzard: Hit ": "地狱秃鹰: 命中",
    "Wailing Beast: Hit ": "哀泣兽: 命中",
    "Sszark The Burning: Hit ": "燃烧者韦布: 命中",
    "Infidel: Hit ": "异教徒: 命中",
    "Spider Magus: Hit ": "蜘蛛巫师: 命中",
    "Ghoul Lord: Hit ": "食尸鬼领主: 命中",
    "Preserved Dead: Hit ": "蜡化木乃伊: 命中",
    "Thorn Beast: Hit ": "荆棘兽: 命中",
    "Fallen: Hit ": "堕落者: 命中",
    "Quill Rat: Hit ": "毛老鼠: 命中",
    "Brute: Hit ": "野蛮人: 命中",
    "You: Hit ": "你: 命中",
    "Fallen Shaman: Hit ": "堕落萨满: 命中",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " (Normal)": " (普通)",
    " (Slow)": " (慢)",
    " (Fast)": " (快)",
    " (Very fast)": " (很快)",
    " (Very slow)": " (很慢)",
    " (Fighter)": " (战士)",
    " (Seller)": " (出售者)",
    " (Assistant)": " (助手)",
    " (✓)": " (✓)",
    ": Blocked": ": 已格挡",
    ": Miss": ": 未命中",
    " during 5s.": " 持续 5 秒。",
    " (Lightning fast)": "（快如闪电）",
    " xp gain / relic)": " 经验增益 / 遗物）",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) \+([\d\.]+)\/s$/,
    /^([\d\.]+)\%.$/,
    /^([\d\.]+)\%$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+)s\)$/,
    /^\(([\d\.]+) \)$/,
    /^\(([\d\.]+)\)$/,
    /^你(.+)$/,
    /^攻击率(.+)$/,
    /^等级(.+)$/,
    /^奖励(.+)$/,
    /^要求等级(.+)$/,
    /^力量(.+)$/,
    /^价格(.+)$/,
    /^防御(.+)$/,
    /^速度(.+)$/,
    /^生命值(.+)$/,
    /^最大(.+)$/,
    /^每次(.+)$/,
    /^闪电(.+)$/,
    /^经验(.+)$/,
    /^灵巧(.+)$/,
    /^火抗(.+)$/,
    /^法力(.+)$/,
    /^毒抗(.+)$/,
    /^增加(.+)$/,
    /^伤害(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Activate (.+) shrines$/, '激活 $1 神殿'],
    [/^Add (.+) poison damage over (.+) seconds$/, '在 $2 秒内增加 $1 点毒伤害'],
    [/^Die (.+) times$/, '死亡 $1 次'],
    [/^Craft (.+) unique items$/, '制作 $1 独特的物品'],
    [/^Sell (.+) items$/, '出售 $1 物品'],
    [/^Level  (.+) \- Damage reduced by (.+)$/, '等级 $1 \- 伤害减少 $2'],
    [/^Level  (.+) \- Life and mana regneration (.+)$/, '等级 $1 \- 生命和法力恢复 $2'],
    [/^Level  (.+) \- Chances to freeze on hit: (.+)$/, '等级 $1 \- 命中时冻结的几率： $2'],
    [/^Level  (.+) \- All resistances (.+)$/, '等级 $1 \- 所有抗性 $2'],
    [/^Unlock (.+) classe$/, '解锁 $1 职业'],
    [/^Unlock (.+) classes$/, '解锁 $1 职业'],
    [/^Selling every (.+)s.$/, '每 $1 秒出售一次。'],
    [/^Kill (.+) monsters$/, '杀死 $1 怪物'],
    [/^Add (.+) cold damage$/, '增加 $1 冰冻伤害'],
    [/^Add (.+) lightning damage$/, '增加 $1 雷电伤害'],
    [/^Add (.+) fire damage$/, '增加 $1 火焰伤害'],
    [/^(.+) died. Xp earned: (.+)$/, '$1 死了。 获得经验：$2'],
    [/^You have been killed by (.+). Xp lost: (.+)$/, '你被 $1 杀死了。 经验值丢失：$2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) \(chance to hit: ([\d\.]+)\%\)$/, '$1（命中率：$2%）'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\% life stolen per hit$/, '每次命中偷取 $1\% 生命值'],
    [/^([\d\.]+)\% mana stolen per hit$/, '每次命中偷取 $1\% 法力值'],
    [/^Reach level ([\d\.]+)$/, '达到等级 $1'],
    [/^Level ([\d\.]+)$/, '等级 $1'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Max damage \+([\d\.,]+) \(base\)$/, '最大伤害 \+$1（基础）'],
    [/^Min damage \+([\d\.,]+) \(base\)$/, '最小伤害 \+$1（基础）'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Reward: (.+) attribute points$/, '奖励：$1 属性点'],
    [/^Reward: (.+) Hireling slot$/, '奖励：$1 雇用插槽'],
    [/^Reward: (.+) xp penalty on death$/, '奖励：$1 死亡时的经验惩罚'],
    [/^Reward: (.+) relics gain$/, '奖励：$1 遗物增益'],
    [/^Reward: (.+) Skill point$/, '奖励：$1 技能点'],
    [/^Reward: Stash size (.+)$/, '奖励：存储大小 $1'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);